SET SERVEROUTPUT ON

EXECUTE GEST_DEPART.VISUALIZAR_DATOS_DEPART2('SALES');
EXECUTE GEST_DEPART.INSERTAR_NUEVO_DEPART('LIMPIEZA', 'SEVILLA');
EXECUTE GEST_DEPART.BORRAR_DEPART(60, 40);
EXECUTE GEST_DEPART.MODIFICAR_LOC_DEPART(20, 'VALENCIA');
EXECUTE GEST_DEPART.VISUALIZAR_DATOS_DEPART(10);--función encapsulada
