SET SERVEROUTPUT ON

ACCEPT DEPARTAMENTO PROMPT 'INTRODUZCA EL NÚMERO DE DEPARTAMENTO';
ACCEPT PORCENTAJE PROMPT 'INTRODUZCA EL PORCENTAJE DE SUELDO PARA SUBIR';
ACCEPT SUELDO PROMPT 'INTRODUZCA LA CANTIDAD DE SUELDO PARA SUBIR';


DECLARE

V_PORCENTAJE NUMBER(2, 0):= &PORCENTAJE;
V_CANT NUMBER(7, 2):= &SUELDO;
V_DEPART NUMBER(2, 0):= &DEPARTAMENTO;
V_NOM EMP.ENAME%TYPE;
v_sal EMP.SAL%TYPE;
v_CantPorcen NUMBER(7, 2);
v_NuevaCant NUMBER(7, 2);


CURSOR Cdepart IS
SELECT ENAME FROM EMP WHERE DEPTNO = V_DEPART;
CURSOR Csueldo(V_NOM VARCHAR2) IS
SELECT SAL FROM EMP WHERE ENAME = V_NOM FOR UPDATE NOWAIT;

BEGIN

OPEN Cdepart;
LOOP
FETCH Cdepart INTO V_NOM;
EXIT WHEN Cdepart%NOTFOUND;
DBMS_OUTPUT.PUT_LINE(V_NOM || ': '); 
OPEN Csueldo(V_NOM);
LOOP
FETCH Csueldo INTO v_sal;
EXIT WHEN Csueldo%NOTFOUND;
v_CantPorcen := v_sal * V_PORCENTAJE / 100;
IF v_CantPorcen >= V_CANT THEN
v_NuevaCant := v_sal + v_CantPorcen;
DBMS_OUTPUT.PUT_LINE('El porcentaje es más beneficioso. 
SALARIO FINAL: ' || v_NuevaCant);
UPDATE EMP SET SAL = SAL + v_CantPorcen WHERE CURRENT OF Csueldo;
v_NuevaCant := 0;
v_CantPorcen := 0;
ELSE
v_NuevaCant := v_sal + V_CANT;
DBMS_OUTPUT.PUT_LINE(': La cantidad es más beneficiosa. SALARIO FINAL: ' || v_NuevaCant);
UPDATE EMP SET SAL = SAL + V_CANT WHERE CURRENT OF Csueldo;
v_NuevaCant := 0;
v_CantPorcen := 0;
END IF;
END LOOP;
CLOSE Csueldo;
END LOOP;
CLOSE Cdepart;
END;