SET SERVEROUTPUT ON

DECLARE

v_apellido EMP.ename%type;
v_fecha EMP.HIREDATE%TYPE;
V_DEPTNO EMP.DEPTNO%TYPE;

CURSOR C1 is
SELECT DEPTNO FROM EMP GROUP BY DEPTNO HAVING COUNT(EMPNO)>2 ORDER BY DEPTNO;

CURSOR C2 (V_DEPTNO NUMBER) IS
SELECT ENAME, HIREDATE FROM EMP WHERE V_DEPTNO = DEPTNO;


BEGIN
OPEN C1;
LOOP
FETCH C1 INTO V_DEPTNO;
EXIT WHEN C1%NOTFOUND;
OPEN C2(V_DEPTNO);
LOOP
FETCH C2 INTO v_apellido, v_fecha;
EXIT WHEN C2%NOTFOUND;
DBMS_OUTPUT.PUT_LINE(v_apellido ||' '|| v_fecha);
END LOOP;
CLOSE C2;
END LOOP;
CLOSE C1;
END;

