SET SERVEROUTPUT ON

ACCEPT V_PROMPT PROMPT 'Introduzca un apellido';

DECLARE 

V_APELLIDO VARCHAR2(20) := &V_PROMPT;
V_EMPNO EMP.EMPNO%TYPE;
V_ENAME EMP.ENAME%TYPE;
V_COUNT INT := 0;

CURSOR C1 IS 
SELECT ENAME, EMPNO FROM EMP WHERE ENAME LIKE '%'||V_APELLIDO||'%';

BEGIN
OPEN C1;
LOOP
FETCH C1 INTO V_ENAME, V_EMPNO;
EXIT WHEN C1%NOTFOUND;
V_COUNT := V_COUNT + 1;
DBMS_OUTPUT.PUT_LINE(V_EMPNO || ' ' || V_ENAME);
END LOOP;
CLOSE C1;
DBMS_OUTPUT.PUT_LINE('NUMERO DE TRABAJADORES: ' || V_COUNT);

END;