create or replace trigger MOTOS
BEFORE INSERT ON VENTA 
FOR EACH ROW

DECLARE

V_EXISTENCIAS MOTOS.EXISTENCIAS%TYPE;
V_COUNT_EX INTEGER;
V_NUMFACT INTEGER;
V_MARCA MOTOS.MARCA%TYPE;
V_MODELO MOTOS.MODELO%TYPE;

BEGIN

SELECT COUNT(EXISTENCIAS) INTO V_COUNT_EX FROM MOTOS;
SELECT COUNT(NUMFACT)INTO V_NUMFACT FROM VENTAS_TOT WHERE FECHA BETWEEN '2017-01-01' AND '2017-05-07' AND MODELO = :NEW.MODELO AND MARCA = :NEW.MARCA;
SELECT EXISTENCIAS INTO V_EXISTENCIAS FROM MOTOS WHERE MODELO = :NEW.MODELO AND MARCA = :NEW.MARCA;
SELECT MODELO, MARCA INTO V_MARCA, V_MODELO FROM MOTOS WHERE MODELO = :NEW.MODELO AND MARCA = :NEW.MARCA;

IF V_COUNT_EX = 0 THEN
IMPRIME('MOTOS AGOTADAS');
ELSE IF V_EXISTENCIAS = 0 THEN
IMPRIME('LAS EXISTENCIAS DE ESTA MOTOCICLETA SON 0');
ELSE
UPDATE MOTOS SET EXISTENCIAS = EXISTENCIAS - 1 WHERE MARCA = :NEW.MARCA AND MODELO = :NEW.MODELO;
IMPRIME('HA COMPRADO UNA ' || V_MARCA || ' ' || V_MODELO || ', QUE EN ESTE AÑO SE HAN VENDIDO ' || V_NUMFACT || ' UNIDADES ESTE AÑO.');
END IF;
END IF;

END;